// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ErrorComp: typeof import('./.vitepress/theme/components/errorComp.vue')['default']
    LoadingComp: typeof import('./.vitepress/theme/components/loadingComp.vue')['default']
    MonitorCard: typeof import('./.vitepress/theme/components/monitorCard.vue')['default']
    MonitorDayAverage: typeof import('./.vitepress/theme/components/monitorDayAverage.vue')['default']
    MonitorHistogram: typeof import('./.vitepress/theme/components/monitorHistogram.vue')['default']
    MonitorMap: typeof import('./.vitepress/theme/components/monitorMap.vue')['default']
    MonitorStatusHeader: typeof import('./.vitepress/theme/components/monitorStatusHeader.vue')['default']
    MonitorStatusLabel: typeof import('./.vitepress/theme/components/monitorStatusLabel.vue')['default']
    MonitorTable: typeof import('./.vitepress/theme/components/monitorTable.vue')['default']
    StatusPage: typeof import('./.vitepress/theme/components/statusPage.vue')['default']
  }
}

export {}
